---

- name: Ensure database is created
  become: yes
  become_user: postgres
  become_method: sudo
  postgresql_db: >
    name={{gogs_db_name}}
    encoding='UTF-8'
    lc_collate='en_US.UTF-8'
    lc_ctype='en_US.UTF-8'
    template='template0'

- name: Ensure user has access to database
  become: yes
  become_user: postgres
  become_method: sudo
  postgresql_user: >
    db={{gogs_db_name}}
    name={{gogs_db_user}}
    password={{gogs_db_password}}
    priv=ALL

- name: Ensure user does not have unnecessary privilege
  become: yes
  become_user: postgres
  become_method: sudo
  postgresql_user: >
    name={{gogs_db_user}}
    role_attr_flags=NOSUPERUSER,NOCREATEDB
